export enum Provincias {
    BUENOSAIRES, CATAMARCA, CHACO, CHUBUT, CORDOBA, CORRIENTES, ENTRERIOS, FORMOSA, JUJUY, LAPAMPA, LARIOJA, MALARGUE, MENDOZA, MISIONES, NEUQUEN, RIONEGRO, SALTAA, SANJUAN, SANLUIS, SANTACRUZ, SANTAFE, SANTIAGODELESTERO, TIERRADELFUEGO, TUCUMAN
}